# Configuration of Hugo
# Guide: https://wowchemy.com/docs/getting-started/
# Hugo Documentation: https://gohugo.io/getting-started/configuration/#all-configuration-settings
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

title: ACoSeMSusTran # Website name
baseURL: 'https://acosemsustran.github.io/' # Website URL

############################
## LANGUAGE
############################

defaultContentLanguage: en
hasCJKLanguage: false
defaultContentLanguageInSubdir: false
removePathAccents: true

############################
## MODULES
############################

module:
  imports:
    - path: github.com/wowchemy/wowchemy-hugo-modules/wowchemy-cms/v5
    - path: github.com/wowchemy/wowchemy-hugo-modules/wowchemy/v5

############################
## ADVANCED
############################

enableGitInfo: false
summaryLength: 30
paginate: 10
enableEmoji: true
enableRobotsTXT: true
footnotereturnlinkcontents: <sup>^</sup>
ignoreFiles: [\.ipynb$, .ipynb_checkpoints$, \.Rmd$, \.Rmarkdown$, _cache$]
permalinks:
  authors: '/author/:slug/'
  event: '/talk/:slug/'
  tags: '/tag/:slug/'
  categories: '/category/:slug/'
  publication_types: '/publication-type/:slug/'
disableAliases: true
outputs:
  home: [HTML, RSS, JSON, WebAppManifest, headers, redirects]
  section: [HTML, RSS]
imaging:
  resampleFilter: lanczos
  quality: 75
  anchor: smart
timeout: 600000
taxonomies:
  tag: tags
  category: categories
  publication_type: publication_types
  author: authors
markup:
  _merge: deep
related:
  threshold: 80
  includeNewer: true
  toLower: true
  indices:
    - name: tags
      weight: 100
    - name: categories
      weight: 70
security:
  _merge: deep
sitemap:
  _merge: deep

collections:
  - name: software
    label: Software
    label_singular: Software
    folder: 'content/software'
    path: '{{slug}}/index'
    filter: {field: "cms_exclude"}
    create: true  # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Subtitle", name: "subtitle", widget: "string", required: false }
      - label: "Publication type"
        name: "publication_types"
        required: true
        default: ["0"]
        widget: "select"
        # Can only have 1 pub. type assigned, but need `multiple` option to save as a Hugo taxonomy list.
        multiple: true
        options:
          - { label: "Uncategorized", value: "0" }
          - { label: "Conference paper", value: "1" }
          - { label: "Journal article", value: "2" }
          - { label: "Preprint / Working Paper", value: "3" }
          - { label: "Report", value: "4" }
          - { label: "Book", value: "5" }
          - { label: "Book section", value: "6" }
          - { label: "Thesis", value: "7" }
          - { label: "Patent", value: "8" }
      - label: "Authors"
        name: "authors"
        required: true
        widget: "list"
      - label: "Author Notes (contributions or affiliations for each author)"
        name: "author_notes"
        required: false
        widget: "list"
      - { label: "DOI", name: "doi", widget: "string", required: false }
      - { label: "Publication", name: "publication", widget: "string", required: false }
      - { label: "Publication (abbreviated)", name: "publication_short", widget: "string", required: false }
      - { label: "Abstract", name: "abstract", widget: "text", required: false }
      - label: "Draft"
        name: "draft"
        widget: "boolean"
        default: false
        required: false
      - label: "Featured"
        name: "featured"
        widget: "boolean"
        default: false
        required: false
      - label: "Tags"
        name: "tags"
        required: false
        widget: "list"
      - label: "Categories"
        name: "categories"
        required: false
        widget: "list"
      - label: "Projects"
        name: "projects"
        required: false
        widget: "list"
      - {label: "Markdown slides (reference a deck in 'content/slides/')", name: "slides", widget: "string", required: false}
      - label: "Featured Image"
        name: "image"
        required: false
        widget: object
        fields:
          - label: "Upload an image named `featured.jpg/png`"
            name: "filename"
            widget: "image"
            default: "featured"
            required: false
            media_library:
              config:
                multiple: false
          - { label: Caption, name: caption, widget: string, required: false }
          - { label: Description for screen readers, name: alt_text, widget: string, required: false }
          - { label: "Where's the focal point in the image? Smart, Center, TopLeft, Top, TopRight, Left, Right, BottomLeft, Bottom, BottomRight.", name: focal_point, widget: string, required: false, default: "Smart" }
          - { label: 'Thumbnail Only?', name: preview_only, widget: boolean, default: false, required: false }
      - { label: "Summary (shortened abstract)", name: "summary", widget: "text", required: false }
      - {label: "Details", name: "body", widget: "markdown", required: false}
      - { label: "Publish this page on", name: "date", widget: "datetime" }
