# Automatic deploy webpage
# Based on: https://www.jameswright.xyz/post/deploy-hugo-academic-using-githubio/
# and: https://github.com/marketplace/actions/hugo-deploy-github-pages

name: Build and Deploy (Scheduled)

# Controls when the action will run. Triggers the workflow on a schedule
on:
  schedule:
    # Execute this task every two days at 04:00 AM
    - cron:  '0 4 */2 * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Checkout main
      uses: actions/checkout@v1
      with:
        submodules: true

    - name: Hugo Deploy GitHub Pages
      uses: JoseAngelMartinB/hugo-deploy-gh-pages@master
      env:
        HUGO_VERSION: 0.98.0
        HUGO_EXTENDED: true
        TARGET_REPO: ACoSeMSusTran/ACoSeMSusTran.github.io
        TOKEN: ${{ secrets.HUGO_DEPLOY_TOKEN }}
        CNAME: acosemsustran.upc.edu
